### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cuamckuu** [cuamckuu/telepub#1]
# TODO

- [ ] Учитывать grouped_id сообщений
- [ ] Разделить в коде выкачку данных и создание epub
- [ ] Генерировать обложку по автарке канала
- [ ] Определять язык?
- [ ] Удалять из имени файла неподдерживаемые символы
- [ ] NLP: Скипать рекламу
- [ ] Поддержка видео
- [ ] Поддержка аудио
- [X] Сжимать картинки
- [ ] Распараллелить сжатие
- [X] Правильно получать rich текст
- [ ] Подставлять содержимое telegra.ph
- [ ] Проверка валидности epub: https://draft2digital.com/book/epubcheck/upload
- [ ] Вытаскивать реакции
